### ISSUE TITLE
Investigate switching away from `got`

### ISSUE THREAD

**Issue by freymend** [freymondz/auraxis-bot#21]
The largest bottleneck in fulfilling commands is Auraxis bot waiting for HTTP requests. `Undici` seems like the best replacement. A drop in replacement seems unlikely so maximizing HTTP performance is the way to go.
 
`Undici` is not only very fast, but `fetch()` is currently being integrated into `Node`. When `fetch()` in `Node` becomes stable we could potentially migrate. The issue with `Undici` is that `fetch()` is experimental right now, breaking changes between versions could make it hard to maintain. The main library is stable but on initial glance seems harder to use compared to `got`. Additionally changing HTTP requests library would necessitate rewriting any error handling.

- [x] `alertMaintenance.js` remainna/auraxis-bot#75
- [x] `alerts.js` remainna/auraxis-bot#75
- [x] `character.js` remainna/auraxis-bot#75
- [x] `population.js` remainna/auraxis-bot#75
- [x] `twitterListener.js` remainna/auraxis-bot#75
- [x] `outfitWars.js` remainna/auraxis-bot#75
- [x] `utils.js` remainna/auraxis-bot#72
