### ISSUE TITLE
General Code clean up

### ISSUE THREAD

**Issue by freymend** [freymondz/auraxis-bot#7]
Simplifying code remove redundancy and take advantage of current JS/Node features. This would be looking at single files and not looking for overall patterns between files. Fix any bugs I find along the way. Have to update JSdocs in each file because there is no way I got them all right.

- [ ]  `alerts.js`
- [ ] `auraxiums.js`
- [ ] `character.js`
- [ ] `directives.js`
- [ ] `implant.js`
- [ ] `leaderboard.js`
- [ ] `population.js`
- [ ] `preASP.js`
- [x] `status.js` remainna/auraxis-bot#57
- [ ] `territory.js`
- [ ] `alertMaintenance.js`
- [ ] `dashboard.js`
- [ ] `deleteMessages.js`
- [x] `messageHandler.js` remainna/auraxis-bot#63
- [ ] `online.js`
- [ ] `openContinents.js`
- [ ] `outfit.js`
- [ ] `stats.js`
- [ ] `subscriptionConfig.js`
- [ ] `subscriptions.js`
- [ ] `trackers.js`
- [x] `twitterListener.js` remainna/auraxis-bot#55
- [ ] `unifiedWSHandler.js` remainna/auraxis-bot#64
- [x] `unifiedWSListener.js` remainna/auraxis-bot#71
- [ ] `utils.js`
